# general settings
name: 001_MRI2024_brain_train_20240123_006_usp_de4
model_type: RealESRNetModel
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

gt_usm: True  # USM the ground-truth

# the first degradation process
resize_prob: [0.0, 0.0, 1.0]  # up, down, keep
resize_range: [1.0, 1.0]
gaussian_noise_prob: 0.0
noise_range: [1, 1]
poisson_scale_range: [0.01, 0.01]
gray_noise_prob: 0.0
jpeg_range: [99, 99]

# the second degradation process
second_blur_prob: 0.0
resize_prob2: [0.0, 0.0, 1.0]  # up, down, keep
resize_range2: [1.0, 1.0]
gaussian_noise_prob2: 0.0
noise_range2: [1, 1]
poisson_scale_range2: [0.01, 0.01]
gray_noise_prob2: 0.0
jpeg_range2: [99, 99]

gt_size: 256
queue_size: 180

# dataset and data loader settings
datasets:
  train:
    name: MRI_Brain01
    type: RealESRGANDataset
    dataroot_gt: datasets/random_fastMRI01/train
    dataroot_lq: datasets/random_fastMRI01/train
    meta_info: datasets/random_fastMRI01/meta_info/meta_info_MRI_Brain2024_usp.txt
    io_backend:
      type: disk

    blur_kernel_size: 1
    kernel_list: ['iso']
    kernel_prob: [0.99]
    sinc_prob: 0.0
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 1
    kernel_list2: ['iso']
    kernel_prob2: [0.99]

    sinc_prob2: 0.0
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.0

    gt_size: 256
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: val_008
    type: PairedImageDataset
    dataroot_gt: datasets/random_fastMRI01/val/raw_image_F01
    dataroot_lq: datasets/random_fastMRI01/val/fixation_01
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 1

# path
path:
  #pretrain_network_g: experiments/pretrained_models/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth / /kaggle/input/net-g-40000-b2024/net_g_40000_b2024.pth
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [5000]
    gamma: 0.5

  total_iter: 5000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 1e3
  save_img: True

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500