# general settings
name: 001_MRI2024_brain_train_20240123_006_diff
model_type: RealESRNetModel
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

gt_usm: True  # USM the ground-truth

high_order_degradation: False # do not use the high-order degradation generation process

# dataset and data loader settings
datasets:
  train:
    name: MRI_Brain01
    type: RealESRGANPairedDataset
    dataroot_gt: datasets/Brain_MRI_2024/train
    dataroot_lq: datasets/Brain_MRI_2024/train
    meta_info: datasets/Brain_MRI_2024/meta_info/meta_info_MRI_Brain2024_pair.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: val_008
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-008
    dataroot_lq: datasets/Brain_MRI_2024/val/008-4
    io_backend:
      type: disk

  val_2:
    name: val_006
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-006
    dataroot_lq: datasets/Brain_MRI_2024/val/006-4
    io_backend:
      type: disk

  val_3:
    name: val_004
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-004
    dataroot_lq: datasets/Brain_MRI_2024/val/004-4
    io_backend:
      type: disk

  val_4:
    name: val_002
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-002
    dataroot_lq: datasets/Brain_MRI_2024/val/002-4
    io_backend:
      type: disk

  val_5:
    name: val_006_4_1
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-006-4-1
    dataroot_lq: datasets/Brain_MRI_2024/val/006-4-1
    io_backend:
      type: disk

  val_6:
    name: val_006_2
    type: PairedImageDataset
    dataroot_gt: datasets/Brain_MRI_2024/val/raw_image-006-2
    dataroot_lq: datasets/Brain_MRI_2024/val/006-2
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 1

# path
path:
  #pretrain_network_g: experiments/pretrained_models/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth / /kaggle/input/net-g-40000-b2024/net_g_40000_b2024.pth
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [40000]
    gamma: 0.5

  total_iter: 40000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 1e4
  save_img: True

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500